import { FullAudit } from '@/types/seo';

export const DEMO_AUDIT: FullAudit = {
  id: 'demo-audit-sample',
  url: 'https://example.com',
  normalizedUrl: 'https://example.com',
  status: 'completed',
  score: 78,
  technicalScore: 82,
  onPageScore: 74,
  contentScore: 79,
  linksScore: 68,
  isDemo: true,
  summary: 'SEO Health Score: 78/100 (Good). The website shows a strong technical foundation with fast server response and valid SSL, but has high-impact opportunities in metadata optimization, image alt tags, and internal link architecture.',
  createdAt: new Date().toISOString(),
  completedAt: new Date().toISOString(),
  pages: [
    {
      id: 'demo-p1',
      url: 'https://example.com',
      statusCode: 200,
      title: 'Example Domain - Modern Web Architecture',
      metaDescription: 'Illustrative examples for documentation, development testing, and standards demonstrations.',
      canonical: 'https://example.com',
      robotsMeta: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      h1Count: 1,
      h1List: ['Example Domain'],
      h2Count: 3,
      h2List: ['Overview', 'Standards Compliance', 'Documentation & Tools'],
      h3Count: 0,
      h3List: [],
      wordCount: 420,
      imageCount: 4,
      missingAltCount: 2,
      images: [
        { src: 'https://example.com/logo.svg', alt: 'Example Domain Logo', hasAlt: true, isAltEmpty: false },
        { src: 'https://example.com/hero.png', alt: '', hasAlt: true, isAltEmpty: true },
        { src: 'https://example.com/chart.png', alt: '', hasAlt: false, isAltEmpty: true },
        { src: 'https://example.com/icon.svg', alt: 'Documentation icon', hasAlt: true, isAltEmpty: false },
      ],
      internalLinkCount: 6,
      externalLinkCount: 2,
      internalLinks: [
        'https://example.com/about',
        'https://example.com/docs',
        'https://example.com/pricing',
        'https://example.com/contact',
        'https://example.com/blog',
        'https://example.com/terms',
      ],
      externalLinks: ['https://www.iana.org/domains/example', 'https://tools.ietf.org/html/rfc2606'],
      responseTimeMs: 142,
      contentType: 'text/html; charset=UTF-8',
      isHttps: true,
      hasRobotsTxt: true,
      hasSitemap: true,
      issues: [],
    },
    {
      id: 'demo-p2',
      url: 'https://example.com/docs',
      statusCode: 200,
      title: 'Documentation',
      metaDescription: null,
      canonical: 'https://example.com/docs',
      robotsMeta: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      h1Count: 1,
      h1List: ['Technical Documentation'],
      h2Count: 4,
      h2List: ['Getting Started', 'API Reference', 'SDKs', 'Troubleshooting'],
      h3Count: 0,
      h3List: [],
      wordCount: 890,
      imageCount: 2,
      missingAltCount: 0,
      images: [
        { src: 'https://example.com/diagram.png', alt: 'API Architecture Diagram', hasAlt: true, isAltEmpty: false },
        { src: 'https://example.com/code.png', alt: 'Code snippet example', hasAlt: true, isAltEmpty: false },
      ],
      internalLinkCount: 4,
      externalLinkCount: 1,
      internalLinks: ['https://example.com', 'https://example.com/about', 'https://example.com/pricing', 'https://example.com/broken-page'],
      externalLinks: ['https://developer.mozilla.org'],
      responseTimeMs: 185,
      contentType: 'text/html; charset=UTF-8',
      isHttps: true,
      hasRobotsTxt: true,
      hasSitemap: true,
      issues: [],
    },
    {
      id: 'demo-p3',
      url: 'https://example.com/about',
      statusCode: 200,
      title: 'About Us',
      metaDescription: 'Learn more about our mission, leadership, and story.',
      canonical: null,
      robotsMeta: 'index, follow',
      viewport: 'width=device-width, initial-scale=1',
      h1Count: 2,
      h1List: ['About Us', 'Our Mission'],
      h2Count: 2,
      h2List: ['The Team', 'Values'],
      h3Count: 0,
      h3List: [],
      wordCount: 310,
      imageCount: 3,
      missingAltCount: 1,
      images: [
        { src: 'https://example.com/team.jpg', alt: '', hasAlt: false, isAltEmpty: true },
        { src: 'https://example.com/office.jpg', alt: 'Office headquarters', hasAlt: true, isAltEmpty: false },
      ],
      internalLinkCount: 3,
      externalLinkCount: 0,
      internalLinks: ['https://example.com', 'https://example.com/docs', 'https://example.com/contact'],
      externalLinks: [],
      responseTimeMs: 160,
      contentType: 'text/html; charset=UTF-8',
      isHttps: true,
      hasRobotsTxt: true,
      hasSitemap: true,
      issues: [],
    },
    {
      id: 'demo-p4',
      url: 'https://example.com/broken-page',
      statusCode: 404,
      title: null,
      metaDescription: null,
      canonical: null,
      robotsMeta: null,
      viewport: null,
      h1Count: 0,
      h1List: [],
      h2Count: 0,
      h2List: [],
      h3Count: 0,
      h3List: [],
      wordCount: 0,
      imageCount: 0,
      missingAltCount: 0,
      images: [],
      internalLinkCount: 0,
      externalLinkCount: 0,
      internalLinks: [],
      externalLinks: [],
      responseTimeMs: 95,
      contentType: 'text/html',
      isHttps: true,
      hasRobotsTxt: true,
      hasSitemap: false,
      issues: [],
    },
  ],
  issues: [
    {
      id: 'tech-robots-pass',
      category: 'TECHNICAL',
      title: 'Valid robots.txt File',
      severity: 'info',
      status: 'pass',
      score: 100,
      description: 'A valid robots.txt file is present and properly allows crawl access to search engine bots.',
      recommendation: 'Keep robots.txt updated whenever you restructure paths or add staging areas.',
      evidence: 'robots.txt found and accessible at https://example.com/robots.txt',
    },
    {
      id: 'tech-sitemap-pass',
      category: 'TECHNICAL',
      title: 'XML Sitemap Detected',
      severity: 'info',
      status: 'pass',
      score: 100,
      description: 'An XML sitemap containing indexed URLs was discovered and verified.',
      recommendation: 'Ensure your sitemap is submitted in Google Search Console.',
      evidence: 'https://example.com/sitemap.xml (HTTP 200)',
    },
    {
      id: 'tech-status-demo-p4',
      category: 'TECHNICAL',
      title: 'Page Returned HTTP Error (404)',
      severity: 'warning',
      status: 'fail',
      score: 0,
      description: 'The crawler encountered a 404 Not Found error when accessing this internal page.',
      recommendation: 'Fix broken links pointing to this missing page or set up a 301 redirect to relevant content.',
      evidence: 'HTTP Status 404 for https://example.com/broken-page',
      pageUrl: 'https://example.com/broken-page',
      pageId: 'demo-p4',
    },
    {
      id: 'tech-canonical-missing-demo-p3',
      category: 'TECHNICAL',
      title: 'Missing Canonical Tag',
      severity: 'warning',
      status: 'warning',
      score: 60,
      description: 'This page does not declare a canonical tag in the `<head>` section.',
      recommendation: 'Add a self-referencing canonical tag `<link rel="canonical" href="https://example.com/about">` to prevent duplicate indexation.',
      evidence: 'No canonical link found',
      pageUrl: 'https://example.com/about',
      pageId: 'demo-p3',
    },
    {
      id: 'onpage-desc-missing-demo-p2',
      category: 'ON_PAGE',
      title: 'Missing Meta Description',
      severity: 'critical',
      status: 'fail',
      score: 0,
      description: 'WHAT: The documentation page is missing a meta description tag.\nWHY: Search engines will generate an automated snippet which often leads to lower click-through rates.\nHOW TO FIX: Add a compelling 120-160 character description summarizing the documentation.',
      recommendation: 'Add a concise, relevant meta description that accurately describes the documentation resources.',
      evidence: 'No meta description tag in <head>',
      pageUrl: 'https://example.com/docs',
      pageId: 'demo-p2',
    },
    {
      id: 'onpage-title-short-demo-p2',
      category: 'ON_PAGE',
      title: 'Title Tag Is Too Short',
      severity: 'warning',
      status: 'warning',
      score: 65,
      description: 'WHAT: The title tag is only 13 characters ("Documentation").\nWHY: Short titles miss opportunities to rank for target keywords and brand identity.\nHOW TO FIX: Expand the title tag to 30-60 characters, e.g. "Developer Documentation & API Guides | Example Domain".',
      recommendation: 'Expand the title tag with relevant target keywords and brand context.',
      evidence: '"Documentation" (13 characters)',
      pageUrl: 'https://example.com/docs',
      pageId: 'demo-p2',
    },
    {
      id: 'onpage-h1-multiple-demo-p3',
      category: 'ON_PAGE',
      title: 'Multiple H1 Headings Detected',
      severity: 'warning',
      status: 'warning',
      score: 70,
      description: 'WHAT: Found 2 separate <h1> headings on the About page ("About Us" and "Our Mission").\nWHY: A single H1 establishes the primary topical focus for search crawlers.\nHOW TO FIX: Keep "About Us" as the primary <h1> and change "Our Mission" to an <h2>.',
      recommendation: 'Consolidate down to one primary `<h1>` heading and convert secondary headers to `<h2>`.',
      evidence: 'Found 2 H1 tags: "About Us", "Our Mission"',
      pageUrl: 'https://example.com/about',
      pageId: 'demo-p3',
    },
    {
      id: 'onpage-img-alt-demo-p1',
      category: 'ON_PAGE',
      title: 'Images Missing Alt Text (2/4)',
      severity: 'warning',
      status: 'warning',
      score: 50,
      description: 'WHAT: 2 images on the homepage lack descriptive alt attributes.\nWHY: Alt attributes are essential for screen readers and enable image search visibility.\nHOW TO FIX: Add descriptive alt attributes reflecting the image content.',
      recommendation: 'Add descriptive alt text to all informative images.',
      evidence: 'Missing on hero.png, chart.png',
      pageUrl: 'https://example.com',
      pageId: 'demo-p1',
    },
    {
      id: 'content-depth-pass-demo-p2',
      category: 'CONTENT',
      title: 'Substantial Content Depth',
      severity: 'info',
      status: 'pass',
      score: 100,
      description: 'The documentation page provides 890 words of informative, structured technical content.',
      recommendation: 'Keep code examples and guides updated with framework releases.',
      evidence: '890 words with code samples',
      pageUrl: 'https://example.com/docs',
      pageId: 'demo-p2',
    },
    {
      id: 'content-moderate-demo-p3',
      category: 'CONTENT',
      title: 'Moderate Content Depth',
      severity: 'info',
      status: 'warning',
      score: 75,
      description: 'WHAT: The About page contains 310 words.\nWHY: Light text can provide limited context for search queries.\nHOW TO FIX: Consider adding sections about company background, leadership profiles, or engineering principles.',
      recommendation: 'Expand page text to thoroughly address user inquiries.',
      evidence: '310 words extracted',
      pageUrl: 'https://example.com/about',
      pageId: 'demo-p3',
    },
    {
      id: 'links-broken-internal-demo-p2',
      category: 'LINKS',
      title: 'Broken Internal Links Detected (1)',
      severity: 'critical',
      status: 'fail',
      score: 20,
      description: 'WHAT: The documentation page links to an internal URL that returns a 404 error.\nWHY: Broken links frustrate users and waste search engine crawl budget.\nHOW TO FIX: Update the link to point to a valid documentation page or remove the broken reference.',
      recommendation: 'Repair links leading to 404 URLs.',
      evidence: 'Links to https://example.com/broken-page (404)',
      pageUrl: 'https://example.com/docs',
      pageId: 'demo-p2',
    },
  ],
  recommendations: [
    {
      priority: 1,
      title: 'Fix Broken Internal Link on Documentation Page',
      description: 'The page https://example.com/docs links to https://example.com/broken-page which returns a 404 error. This degrades user trust and wastes crawl allocation.',
      impact: 'high',
      difficulty: 'easy',
      affectedPages: 'https://example.com/docs',
      howToFix: 'Locate the anchor tag pointing to /broken-page and replace it with the live destination URL or remove it.',
    },
    {
      priority: 2,
      title: 'Add Missing Meta Description to Documentation',
      description: 'The docs page lacks a meta description. Adding a clear 120-160 character description will improve SERP snippet presentation.',
      impact: 'high',
      difficulty: 'easy',
      affectedPages: 'https://example.com/docs',
      howToFix: 'Add `<meta name="description" content="Explore developer guides, API specifications, and code examples for Example Domain.">` in the `<head>`.',
    },
    {
      priority: 3,
      title: 'Add Descriptive Alt Text to 2 Homepage Images',
      description: 'Hero and chart images on the homepage have empty alt attributes. Adding descriptive text improves accessibility and image SEO.',
      impact: 'medium',
      difficulty: 'easy',
      affectedPages: 'https://example.com',
      howToFix: 'Add informative alt attributes such as `alt="Example Domain platform overview illustration"`.',
    },
    {
      priority: 4,
      title: 'Optimize Short Title Tag on Documentation',
      description: 'Expand the 13-character title "Documentation" to include key search phrases such as "API Documentation & Developer Guides | Example Domain".',
      impact: 'medium',
      difficulty: 'easy',
      affectedPages: 'https://example.com/docs',
      howToFix: 'Update `<title>Developer Documentation & API Reference | Example Domain</title>`.',
    },
    {
      priority: 5,
      title: 'Add Canonical Tag to About Page',
      description: 'Add a self-referencing canonical tag to prevent accidental duplicate content issues.',
      impact: 'low',
      difficulty: 'easy',
      affectedPages: 'https://example.com/about',
      howToFix: 'Add `<link rel="canonical" href="https://example.com/about">` in the `<head>`.',
    },
  ],
  quickWins: [
    'Repair the 1 broken internal link in the documentation section.',
    'Add a compelling meta description to https://example.com/docs.',
    'Fill in descriptive alt text on the 2 homepage images.',
    'Expand the documentation title tag to 45+ characters.',
  ],
};
